test:node:
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - docker run -v $PWD:/src -w /src node npm run ci
    - docker run -v $PWD:/src -w /src npm run lint
    - docker run -v $PWD:/src -w /src npm run test
