test:node:
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run lint
    - npm run test


test:docker:
  image: docker:stable
  script:
    - apk add make
    - make all
