language: generic

services:
  - docker

jobs:
  include:
    # A stage is a group of jobs that are allowed to run in parallel. 
    - stage: test
      script: make node package enable integration
    - stage: deploy
      script: skip
      before_deploy:
      - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin;
      deploy:
        provider: script
        script: make push
        on:
          branch: master
    - stage: verify
      install: skip
      script: make pull integration

stages:
  - test
  - deploy
  - verify