language: generic

services:
  - docker

jobs:
  include:
    - name: test
      script: make node package enable integration
    - name: deploy
      script: skip
      before_deploy:
      - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin;
      deploy:
        provider: script
        script: make push
        on:
          branch: master
    - name: verify
      install: skip
      script: make pull
